# Generated by Django 5.2.1 on 2025-05-12 19:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hujjat',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Hujjat',
                'verbose_name_plural': 'Hujjat',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Xizmatlar',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('xizmat_turi', models.CharField(choices=[('NXX', 'NXX'), ('MEDIA', 'MEDIA'), ('SHARTNOMA', 'SHARTNOMA'), ('MAQOLA', 'MAQOLA')], max_length=20)),
                ('ism_familiya', models.CharField(max_length=255)),
                ('izoh', models.TextField()),
                ('phone', models.CharField(max_length=20)),
                ('file', models.FileField(upload_to='xizmatlar/')),
                ('hujjat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shablon.hujjat')),
            ],
            options={
                'verbose_name': 'Xizmatlar',
                'verbose_name_plural': 'Xizmatlar',
                'ordering': ['xizmat_turi'],
            },
        ),
    ]
